# Generated by Django 4.2.5 on 2023-11-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_photo',
            field=models.CharField(max_length=1000000000000000000000, null=True),
        ),
    ]
